---
title: "Documenting code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#` read file and returns a tbl of the data
#` 
#` @param filename A character string giving the name of the file
#`        which is needed to read
#` 
#` @importFrom readr read_csv
#` 
#` @importFrom dplyr tbl_df
#` 
#` @export
#`
#` @examples
#` 
#` \dontrun{files <- fars_read('filename_1.csv')}
#` 
#` @return This function return file xxx does not exist if the input
#`         file can not be founded, else the file would be readed.

fars_read <- function(filename) {
        if(!file.exists(filename))
                stop("file '", filename, "' does not exist")
        data <- suppressMessages({
                readr::read_csv(filename, progress = FALSE)
        })
        dplyr::tbl_df(data)
}

#` make a file name
#`
#` this function is used to get the record year from .csv.bz2 file
#` @param year A character that is derived from accident_2013, 2014,
#`        and 2015 files and needed to be translated into integer
#` 
#` @return this function returns the file name.
#`
#` @source extdate/accident_year.csv.bz2
#`
#` @export
#`
#` @examples newfile <- \dontrun{make_filename(2014)}

make_filename <- function(year) {
        year <- as.integer(year)
        sprintf("accident_%d.csv.bz2", year)
}

#` catch the years
#`
#` this function is used to get the file of the input years
#`
#` @param year A new builded interger contains the month and year
#`
#` @importFrom dplyr mutate
#`
#` @importFrom dplyr select
#`
#` @examples {dontrun/fars_read_years(c(2013, 2014, 2015))}
#`
#` @return If the function successfully read the file then the value 
#`         of months will be added to the existing value of years, 
#`         otherwise the function will return an "invalid year: xx"
#`         message
fars_read_years <- function(years) {
        lapply(years, function(year) {
                file <- make_filename(year)
                tryCatch({
                        dat <- fars_read(file)
                        dplyr::mutate(dat, year = year) %>% 
                                dplyr::select(MONTH, year)
                }, error = function(e) {
                        warning("invalid year: ", year)
                        return(NULL)
                })
        })
}

#` summarize the information of years
#`
#` @param years this function use the previous defined function 
#`        fars_read_years to get the data list and combind data rows, 
#`        then the list would grouped by year and MONTH, then pass to 
#`        the summarize of rows, finally the data frame will be 
#`        displayed with year and num.
#`
#` @importFrom dplyr bind_rows
#`
#` @importFrom dplyr group_by
#`
#` @importFrom dplyr summarize
#`
#` @importFrom tidyr spread
#`
#` @examples {dontrun/fars_summarize_years(c(2013, 2014, 2015))}
#`
#` @return this function will return a data frame.
#`
fars_summarize_years <- function(years) {
        dat_list <- fars_read_years(years)
        dplyr::bind_rows(dat_list) %>% 
                dplyr::group_by(year, MONTH) %>% 
                dplyr::summarize(n = n()) %>%
                tidyr::spread(year, n)
}

#` Title fars_map_state
#`
#` This function plot the state map with the location
#`
#` @param state.num the number of a states
#`
#` @param year The value of years
#`
#` @return A plot or some plots based on latitude and longitude from
#`         the data file
#`
#` @importFrom dplyr filter
#`
#` @importFrom maps map
#`
#` @importFrom graphics points
#`
#` @examples \dontrun{fars_map_state(1, 2013)}
#` 
fars_map_state <- function(state.num, year) {
        filename <- make_filename(year)
        data <- fars_read(filename)
        state.num <- as.integer(state.num)

        if(!(state.num %in% unique(data$STATE)))
                stop("invalid STATE number: ", state.num)
        data.sub <- dplyr::filter(data, STATE == state.num)
        if(nrow(data.sub) == 0L) {
                message("no accidents to plot")
                return(invisible(NULL))
        }
        is.na(data.sub$LONGITUD) <- data.sub$LONGITUD > 900
        is.na(data.sub$LATITUDE) <- data.sub$LATITUDE > 90
        with(data.sub, {
                maps::map("state", ylim = range(LATITUDE, na.rm = TRUE),
                          xlim = range(LONGITUD, na.rm = TRUE))
                graphics::points(LONGITUD, LATITUDE, pch = 46)
        })
}